-- ColorAttempt: RGB arrays -> HSB scalars
ALTER TABLE "ColorAttempt" DROP COLUMN "targetRgb",
DROP COLUMN "guessRgb";

ALTER TABLE "ColorAttempt"
ADD COLUMN "targetHue" DOUBLE PRECISION NOT NULL,
ADD COLUMN "targetSaturation" DOUBLE PRECISION NOT NULL,
ADD COLUMN "targetBrightness" DOUBLE PRECISION NOT NULL,
ADD COLUMN "guessHue" DOUBLE PRECISION NOT NULL,
ADD COLUMN "guessSaturation" DOUBLE PRECISION NOT NULL,
ADD COLUMN "guessBrightness" DOUBLE PRECISION NOT NULL;
